dataset:
  name: "msmarco_passage"
  topics_variant:
    - "test-2019"
    - "test-2020"
  qrels_variant:
    - "test-2019"
    - "test-2020"

experiment:
  # Nome logico dello scorer, cioè quello usato dal tuo codice in get_scorer/base_scorer.
  scorer: "metadata_qualt5"
  index_scorer_name: "metadata_qualt5_CONCAT"
  # Nome specifico dell'esperimento/cache.
  # Verrà usato per nominare la cartella degli indici.
  scorer_output_name: "metadata_qualt5_CONCAT"

  
  # Cache effettiva da usare.
  # Lo script cercherà:
  # /data/data-sacco/cache/metadata_qualt5_msmarco_passage_CONCAT.cache
  cache_file: "metadata_qualt5_msmarco_passage_CONCAT.cache"

  threshold: 0.60
  restart_cache: false
  retriever: "all"

paths:
  cache_dir: "/data/data-sacco/cache"
  indexes_dir: "/data/data-sacco/indexes"
  results_dir: "./results2"
  runs_dir: "/data/data-sacco/runs"
  full_runs_dir: "/data/data-sacco/runs/runs_full_msmarco_all_trec"

scorers:
  finetuned_qualt5:
    model_name_or_path: "/home/sacco/metaqual/outputs/qt5-supervised-t5-base/checkpoint-10000"
    batch_size: 100
    max_length: 512
    device: "cuda"

  metadata_qualt5:
    model_name_or_path: "/home/sacco/metaqual/outputs/metadata-qualt5-metaprefix-dec2-nolm-h256-lr1e5-5k-cacheMP"
    metadata_path: "/home/sacco/data/msmarco_passage/msmarco_passage_lexical_metadata.parquet"

    lexical_scaler_path: "/home/sacco/metaqual/outputs/metadata-qualt5-metaprefix-dec2-nolm-h256-lr1e5-5k-cacheMP/lexical_metadata_scaler.pkl"
    metadata_scaler_path: "/home/sacco/metaqual/outputs/metadata-qualt5-metaprefix-dec2-nolm-h256-lr1e5-5k-cacheMP/lexical_metadata_scaler.pkl"

    embedding_scaler_path: "/home/sacco/metaqual/outputs/metadata-qualt5-metaprefix-dec2-nolm-h256-lr1e5-5k-cacheMP/embedding_metadata_scaler.pkl"
    token_scaler_path: "/home/sacco/metaqual/outputs/metadata-qualt5-metaprefix-dec2-nolm-h256-lr1e5-5k-cacheMP/token_metadata_scaler.pkl"

    batch_size: 100
    max_length: 512
    device: "cuda"

    scoring_mode: "true_logprob"
    allow_missing_metadata: false

    metadata_fusion_mode: "concat_tokens"
    metadata_dropout: 0.1
    metadata_mlp_hidden_dim: 256
    attention_heads: 8
    use_meta_ffn: true
    normalize_metadata_features: false
    unfreeze_last_n_decoder_blocks: 1
    unfreeze_lm_head: true

    metadata_feature_groups:
      lexical:
        - length_tokens
        - avg_token_length
        - unique_token_ratio
        - repetition_ratio
        - lexical_entropy
        - stopword_ratio
        - content_word_ratio
      embedding:
        - embedding_l1_norm
        - embedding_l2_norm
        - embedding_linf_norm
        - embedding_mean
        - embedding_variance
        - near_zero_fraction
      token:
        - mean_token_norm
        - std_token_norm
        - max_token_norm
        - token_norm_entropy
        - token_to_passage_similarity_mean

advanced:
  chunk_size: 100000
  batch_size: 32